= TRC-721

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/contracts/api/token/erc721

This set of interfaces, contracts, and utilities is all related to the https://github.com/tronprotocol/tips/blob/master/tip-721.md[TRC-721 Non-Fungible Token Standard] (TIP-721, the TRON-side analogue of EIP-721).

TIP: For a walk through on how to create a TRC-721 token read our xref:ROOT:trc721.adoc[TRC-721 guide].

The standard specifies four interfaces:

* {ITRC721}: Core functionality required in all compliant implementation.
* {ITRC721Metadata}: Optional extension that adds name, symbol, and token URI, almost always included.
* {ITRC721Enumerable}: Optional extension that allows enumerating the tokens on chain, often not included since it requires large gas overhead.
* {ITRC721Receiver}: An interface that must be implemented by contracts if they want to accept tokens through `safeTransferFrom`.

OpenZeppelin Contracts provides implementations of all four interfaces:

* {TRC721}: The core and metadata extensions, with a base URI mechanism.
* {TRC721Enumerable}: The enumerable extension.
* {TRC721Holder}: A bare bones implementation of the receiver interface.

Additionally there are a few of other extensions:

* {TRC721Consecutive}: An implementation of https://eips.ethereum.org/EIPS/eip-2309[ERC-2309] for minting batches of tokens during construction, in accordance with TRC-721.
* {TRC721URIStorage}: A more flexible but more expensive way of storing metadata.
* {TRC721Votes}: Support for voting and vote delegation.
* {TRC721Royalty}: A way to signal royalty information following ERC-2981.
* {TRC721Pausable}: A primitive to pause contract operation.
* {TRC721Burnable}: A way for token holders to burn their own tokens.
* {TRC721Wrapper}: Wrapper to create a TRC-721 backed by another TRC-721, with deposit and withdraw methods. Useful in conjunction with {TRC721Votes}.

NOTE: This core set of contracts is designed to be unopinionated, allowing developers to access the internal functions in TRC-721 (such as <<TRC721-_mint-address-uint256-,`_mint`>>) and expose them as external functions in the way they prefer.

== Core

{{ITRC721}}

{{ITRC721Metadata}}

{{ITRC721Enumerable}}

{{TRC721}}

{{TRC721Enumerable}}

{{ITRC721Receiver}}

== Extensions

{{TRC721Pausable}}

{{TRC721Burnable}}

{{TRC721Consecutive}}

{{TRC721URIStorage}}

{{TRC721Votes}}

{{TRC721Royalty}}

{{TRC721Wrapper}}

== Utilities

{{TRC721Holder}}

{{TRC721Utils}}
