= TRC-1155

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/contracts/api/token/erc1155

This set of interfaces and contracts are all related to the https://github.com/tronprotocol/tips/blob/master/tip-1155.md[TRC-1155 Multi Token Standard] (TIP-1155, the TRON-side analogue of EIP-1155).

The standard consists of three interfaces which fulfill different roles, found here as {ITRC1155}, {ITRC1155MetadataURI} and {ITRC1155Receiver}.

{TRC1155} implements the mandatory {ITRC1155} interface, as well as the optional extension {ITRC1155MetadataURI}, by relying on the substitution mechanism to use the same URI for all token types, dramatically reducing gas costs.

Additionally there are multiple custom extensions, including:

* designation of addresses that can pause token transfers for all users ({TRC1155Pausable}).
* destruction of own tokens ({TRC1155Burnable}).

NOTE: This core set of contracts is designed to be unopinionated, allowing developers to access the internal functions in TRC-1155 (such as <<TRC1155-_mint-address-uint256-uint256-bytes-,`_mint`>>) and expose them as external functions in the way they prefer.

== Core

{{ITRC1155}}

{{ITRC1155MetadataURI}}

{{TRC1155}}

{{ITRC1155Receiver}}

== Extensions

{{TRC1155Pausable}}

{{TRC1155Burnable}}

{{TRC1155Supply}}

{{TRC1155URIStorage}}

== Utilities

{{TRC1155Holder}}

{{TRC1155Utils}}
