= Cross chain interoperability

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/contracts/api/crosschain

This directory contains contracts for sending and receiving cross chain messages that follows the ERC-7786 standard.

* {CrosschainLinked}: helper to facilitate communication between a contract on one chain and counterparts on remote chains through ERC-7786 gateways.
* {TRC7786Recipient}: generic ERC-7786 crosschain contract that receives messages from a trusted gateway.

Additionally there are multiple bridge constructions:

* {BridgeFungible}: Core bridging logic for crosschain TRC-20 transfer. Used by {BridgeTRC20}, {BridgeTRC7802} and {TRC20Crosschain},
* {BridgeTRC20}: Standalone bridge contract to connect a TRC-20 token contract with counterparts on remote chains,
* {BridgeTRC7802}: Standalone bridge contract to connect an ERC-7802 token contract with counterparts on remote chains.

== Helpers

{{CrosschainLinked}}

{{TRC7786Recipient}}

== Bridges

{{BridgeFungible}}

{{BridgeTRC20}}

{{BridgeTRC7802}}